version: '3'
services:

  aggregator:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URI=postgresql://applifting:applifting@postgres/applifting
      - CLOUD_URI=https://python.exercise.applifting.cz/
      - ACCESS_TOKEN
    entrypoint: applifting-demo
    ports:
      - "80:8000"
    depends_on:
      - postgres
    networks:
      - internal

  watcher:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URI=postgresql://applifting:applifting@postgres/applifting
      - CLOUD_URI=https://python.exercise.applifting.cz/
      - ACCESS_TOKEN
    entrypoint: remote-mock
    depends_on:
      - postgres
    networks:
      - internal

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=applifting
      - POSTGRES_PASSWORD=applifting
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:
    driver: bridge
